version: '3'

tasks:
  default:
    desc: Builds the project
    cmds:
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug {{.CLI_ARGS}}
      - cmake --build build --parallel

  clean:
    desc: Cleans the project
    cmds:
      - rm -rf build

  release:
    desc: Builds the project in release mode
    cmds:
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release {{.CLI_ARGS}}
      - cmake --build build --parallel

  format:
    desc: Formats the project
    cmds:
      - treefmt {{.CLI_ARGS}}
