version: '3'

tasks:
  default:
    desc: Builds the project
    cmds:
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug {{.CLI_ARGS}}
      - cmake --build build --parallel

  test:
    desc: Builds the project and runs tests
    cmds:
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
      - cmake --build build --parallel
      - ctest --test-dir build --output-on-failure {{.CLI_ARGS}}

  clean:
    desc: Cleans the project
    cmds:
      - rm -rf build

  release:
    desc: Builds the project in release mode
    cmds:
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release {{.CLI_ARGS}}
      - cmake --build build --parallel

  format:
    desc: Formats the project
    cmds:
      - treefmt {{.CLI_ARGS}}
